name: Demo Environment Variables

on:
  push:
    branches: [main]

jobs:
  show-variables:
    name: Show Variables
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        echo "BUILD_TIMESTAMP=$(date)" >> $GITHUB_ENV

    - name: Access environment variables
      run: |
        echo "Build ran at $BUILD_TIMESTAMP"
